when@prod:
    services:
        _defaults:
            autowire: true

        Inpsyde\LogzIoMonolog\Handler\LogzIoHandler:
            arguments:
                $token: '%env(LOGZ_IO_TOKEN)%'
                $host: !php/enum Inpsyde\LogzIoMonolog\Enum\Host::EuCentral1

        Datana\LogzIo\Handler\Logger\Processor\AddApplicationNameProcessor:
            arguments:
                - '%env(LOGZ_IO_APPLICATION_NAME)%'
            tags: ['monolog.processor']
